<a href="https://colab.research.google.com/github/jjlee6496/one-by-one/blob/main/%ED%81%AC%EB%A1%A4%EB%A7%81/%EB%B9%84%EC%A0%95%ED%98%95%20%EC%97%91%EC%85%80%20%ED%8C%8C%ED%8C%8C%EA%B3%A0%20%EB%B2%88%EC%97%AD%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# import

In [ ]:
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver/usr/bin
!pip install selenium

In [9]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.service import Service 
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
import random

In [8]:
options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--incognito')
options.add_experimental_option('excludeSwitches', ['enable-logging'])

# 함수
[참고링크1](https://wookidocs.tistory.com/124)  
[참고링크2](https://stackoverflow.com/questions/72773206/selenium-python-attributeerror-webdriver-object-has-no-attribute-find-el)

In [26]:
def translate(text_list, lang):
  url = f'https://papago.naver.com/?sk={lang}&tk=ko'
  res = []

  browser = webdriver.Chrome('chromedriver',options=options)
  browser.get(url)
  browser.implicitly_wait(2)
  input_box = browser.find_element(By.CSS_SELECTOR,'textarea#txtSource')
  button = browser.find_element(By.CLASS_NAME,'btn_text_clse___1Bp8a')
  for i in text_list:
    if i == '-':
      res.append("")
    else:
      input_box.clear()
      input_box.send_keys(i)
      time.sleep(random.uniform(2,4))
      target_text = browser.find_element(By.CSS_SELECTOR,'div#txtTarget').text
      #print(target_text)
      res.append(target_text)
      button.click()
      time.sleep(3)

   # print('종료')
  return res

# 실행

In [41]:
data = pd.read_excel("123.xlsx",header=None) # 입력파일

data = data.astype("string")
data.columns = data.columns.astype('string')

data2 = pd.DataFrame()
data

              0     1      2
0            hi  <NA>   <NA>
1          <NA>  <NA>   <NA>
2          <NA>  <NA>   <NA>
3          <NA>  <NA>  Hello
4          <NA>  <NA>   <NA>
5  rnasterpiece  <NA>   <NA>
6          <NA>  <NA>   <NA>
7          <NA>  <NA>   <NA>
8          <NA>  <NA>   <NA>
9          <NA>   Bye   <NA>

In [43]:
lang = 'en' #일어: ja
idx = 1
start = time.time() #시작시간 측정용
for cols in data.columns:
  vocab = []
  vocab = data[cols].to_string(index=False).replace('<NA>', "-").replace(', dtype: string', "").replace("Name:" + cols, "").split()
  print(f"{idx}번째 열 번역중")
  data2[cols] = translate(vocab, lang)
  print(f"{idx}번째 열 번역완료")
  idx += 1
print(f"실행시간: {time.time()-start} 초") #실행시간 출력
data2.to_excel('translated.xlsx', index=False, header=False) #출력파일

1번째 열 번역중
1번째 열 번역완료
2번째 열 번역중
2번째 열 번역완료
3번째 열 번역중
3번째 열 번역완료
실행시간: 32.69086527824402 초

In [44]:
pd.read_excel('translated.xlsx')

    안녕 Unnamed: 1 Unnamed: 2
0  NaN        NaN        NaN
1  NaN        NaN        NaN
2  NaN        NaN         안녕
3  NaN        NaN        NaN
4   명작        NaN        NaN
5  NaN        NaN        NaN
6  NaN        NaN        NaN
7  NaN        NaN        NaN
8  NaN        안녕.        NaN